=== galina-p-tuwien/digital_guidelines/examples/DTD_Partial_Algo2.dtd
<!ELEMENT alg:AlgorithmLibrary (alg:Algorithms, alg:Connections)>
<!ATTLIST alg:AlgorithmLibrary xmlns:alg CDATA "">
<!ATTLIST alg:AlgorithmLibrary xmlns:xi CDATA #IMPLIED>
<!ATTLIST alg:AlgorithmLibrary xmlns:xsi CDATA "">
<!ATTLIST alg:AlgorithmLibrary xsi:schemaLocation CDATA "">

<!ELEMENT alg:Algorithms (alg:Algorithm*, xi:include*)>
<!ELEMENT alg:Connections (alg:Connection*)>

<!ELEMENT alg:Algorithm (alg:Inputs, alg:Outputs)>
<!ATTLIST alg:Algorithm name CDATA "">
                <!ATTLIST alg:Algorithm id ID #IMPLIED>
<!ELEMENT alg:Inputs (alg:Input+)>
<!ELEMENT alg:Input (alg:Type)>
<!ATTLIST alg:Input name CDATA #REQUIRED>
<!ATTLIST alg:Input id ID #IMPLIED>
<!ATTLIST alg:Input semantic_tag CDATA #REQUIRED>
<!ATTLIST alg:Input unit CDATA #REQUIRED>
<!ELEMENT alg:Outputs (alg:Output+)>
<!ELEMENT alg:Output (alg:Type)>
<!ATTLIST alg:Output name CDATA #REQUIRED>
<!ATTLIST alg:Output id ID #IMPLIED>
<!ATTLIST alg:Output semantic_tag CDATA #REQUIRED>
<!ATTLIST alg:Output unit CDATA #REQUIRED>

<!ELEMENT alg:Type EMPTY>
<!ATTLIST alg:Type base_type CDATA #REQUIRED>
<!ATTLIST alg:Type multiplicity CDATA #REQUIRED>
<!ATTLIST alg:Type base_type CDATA #REQUIRED>

<!ELEMENT alg:Connection EMPTY>
<!ATTLIST alg:Connection source_algorithm CDATA #REQUIRED>
<!ATTLIST alg:Connection source_output CDATA #REQUIRED>
<!ATTLIST alg:Connection target_algorithm CDATA #REQUIRED>
<!ATTLIST alg:Connection tagret_input CDATA #REQUIRED>

<!ELEMENT xi:include (xi:fallback)>
<!ATTLIST xi:include href CDATA #REQUIRED>
<!ATTLIST xi:include xpointer CDATA #REQUIRED>
<!ELEMENT xi:fallback EMPTY>

=== galina-p-tuwien/digital_guidelines/examples/Algorithm_Test04.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE alg:AlgorithmLibrary SYSTEM "DTD_Partial_Algo2.dtd">
<alg:AlgorithmLibrary xmlns:alg="https://github.com/galina-p-tuwien/digital_guidelines/algorithm"
						xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
						xsi:schemaLocation="https://github.com/galina-p-tuwien/digital_guidelines/algorithm XML_Schema_Algo2.xsd">

	<alg:Algorithms>
		<alg:Algorithm name="AreaOfRect" id="length_based.AreaOfRect">
			<alg:Inputs>
				<alg:Input name="length" id="length_based.length" semantic_tag="ISO.XYZ.a" unit="m">
					<alg:Type base_type="Decimal" multiplicity="Single"/>
				</alg:Input>
				<alg:Input name="width" id="length_based.width" semantic_tag="ISO.XYZ.b" unit="m">
					<alg:Type base_type="Decimal" multiplicity="Single"/>
				</alg:Input>
			</alg:Inputs>
			<alg:Outputs>
				<alg:Output name="area" id="length_based.area" semantic_tag="ISO.XYZ.A" unit="m²">
					<alg:Type base_type="Decimal" multiplicity="Single"/>
				</alg:Output>
			</alg:Outputs>
		</alg:Algorithm>
		
	</alg:Algorithms>


	<alg:Connections>
		
	</alg:Connections>

	
	
</alg:AlgorithmLibrary>

=== galina-p-tuwien/digital_guidelines/examples/ISO6946_Test01.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE alg:AlgorithmLibrary SYSTEM "DTD_Partial_Algo2.dtd">
<alg:AlgorithmLibrary xmlns:alg="https://github.com/galina-p-tuwien/digital_guidelines/algorithm"
				  xmlns:xi="http://www.w3.org/2001/XInclude"
				  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				  xsi:schemaLocation="https://github.com/galina-p-tuwien/digital_guidelines/algorithm XML_Schema_Algo2.xsd">

    <alg:Algorithms>
        <alg:Algorithm id="ISO.6946.Section.6.5.2.EQ1" name="Thermal transmittance">
            <alg:Inputs>
                <alg:Input id="ISO.6946.Section.6.5.2.EQ1.R_tot" name="total thermal resistance"
                semantic_tag="ISO.6946:2017.Section.6.5.2.R_tot" unit="m²K/W">
                    <alg:Type base_type="Double" multiplicity="Single"/>
                </alg:Input>
            </alg:Inputs>
            <alg:Outputs>
                <alg:Output id="ISO.6946.Section.6.5.2.EQ1.U" name="thermal transmittance" 
                semantic_tag="ISO.6946:2017.Section.4.1.U" unit="W/(m²K)">
                    <alg:Type base_type="Double" multiplicity="Single"/>
                </alg:Output>
            </alg:Outputs>
        </alg:Algorithm>

        <alg:Algorithm id="ISO.6946.Section.6.7.1.1.EQ3" name="Thermal resistance of homogeneous layers">
            <alg:Inputs>
                <alg:Input id="ISO.6946.Section.4.1.d" name="layer thickness" semantic_tag="ISO.6946:2017.Section.4.1.d" unit="m">
                    <alg:Type base_type="Double" multiplicity="Single"/>
                </alg:Input>
                <alg:Input id="ISO.6946.Section.4.1.λ" name="design thermal conductivity" semantic_tag="ISO.6946:2017.Section.4.1.λ" unit="W/(mK)">
                    <alg:Type base_type="Double" multiplicity="Single"/>
                </alg:Input>
            </alg:Inputs>
            <alg:Outputs>
                <alg:Output id="ISO.6946.Section.4.1.R" name="thermal resistance" semantic_tag="ISO.6946:2017.Section.4.1.R" unit="m²K/W">
                    <alg:Type base_type="Double" multiplicity="Single"/>
                </alg:Output>
            </alg:Outputs>
        </alg:Algorithm>

        <alg:Algorithm id="ISO.6946.Section.6.7.1.2.EQ4" name="Total thermal resistance">
            <alg:Inputs>
                <alg:Input id="ISO.6946.Section.6.3.R_si" name="internal surface resistance" semantic_tag="ISO.6946:2017.Section.6.3.R_si" unit="m²K/W">
                    <alg:Type base_type="Double" multiplicity="Single"/>
                </alg:Input>
                <alg:Input id="ISO.6946.Section.6.3.R_se" name="external surface resistance" semantic_tag="ISO.6946:2017.Section.6.3.R_se" unit="m²K/W">
                    <alg:Type base_type="Double" multiplicity="Single"/>
                </alg:Input>
                <alg:Input id="ISO.6946.Section.6.7.1.2.EQ4.R_i" name="thermal resistances" semantic_tag="ISO.6946:2017.Section.4.1.R" unit="m²K/W">
                    <alg:Type base_type="Double" multiplicity="Array"/>
                </alg:Input>
            </alg:Inputs>
            <alg:Outputs>
                <alg:Output id="ISO.6946.Section.6.7.1.2.EQ4.R_tot" name="total thermal resistance" semantic_tag="ISO.6946:2017.Section.6.5.2.R_tot" unit="m²K/W">
                    <alg:Type base_type="Double" multiplicity="Single"/>
                </alg:Output>
            </alg:Outputs>
        </alg:Algorithm>

    </alg:Algorithms>

    <alg:Connections>
        <alg:Connection source_algorithm="ISO.6946.Section.6.7.1.2.EQ4" source_output="ISO.6946.Section.6.7.1.2.EQ4.R_tot" 
                        target_algorithm="ISO.6946.Section.6.5.2.EQ1" tagret_input="ISO.6946.Section.6.5.2.EQ1.R_tot" />
        <alg:Connection source_algorithm="ISO.6946.Section.6.7.1.1.EQ3" source_output="ISO.6946.Section.4.1.R" 
                        target_algorithm="ISO.6946.Section.6.7.1.2.EQ4" tagret_input="ISO.6946.Section.6.7.1.2.EQ4.R_i" />
    </alg:Connections>

</alg:AlgorithmLibrary>

=== galina-p-tuwien/digital_guidelines/examples/Algorithm_Test03.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE alg:AlgorithmLibrary SYSTEM "DTD_Partial_Algo2.dtd">
<alg:AlgorithmLibrary xmlns:alg="https://github.com/galina-p-tuwien/digital_guidelines/algorithm"
				  xmlns:xi="http://www.w3.org/2001/XInclude"
				  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				  xsi:schemaLocation="https://github.com/galina-p-tuwien/digital_guidelines/algorithm XML_Schema_Algo2.xsd">

	<alg:Algorithms>
		<alg:Algorithm name="VolumeOfBox" id="length_based.VolumeOfBox">
			<alg:Inputs>
				<alg:Input name="baseArea" id="length_based.baseArea" semantic_tag="ISO.XYZ.A" unit="m²">
					<alg:Type base_type="Decimal" multiplicity="Single"/>
				</alg:Input>
				<alg:Input name="height" id="length_based.height" semantic_tag="ISO.XYZ.h" unit="m">
					<alg:Type base_type="Decimal" multiplicity="Single"/>
				</alg:Input>
			</alg:Inputs>
			<alg:Outputs>
				<alg:Output name="volume" id="length_based.volume" semantic_tag="ISO.XYZ.V" unit="m³">
					<alg:Type base_type="Decimal" multiplicity="Single"/>
				</alg:Output>
			</alg:Outputs>
		</alg:Algorithm>

		<!-- <xi:include href="Algorithm_TestXInclude.xml" xpointer="x">
			<xi:fallback></xi:fallback>
		</xi:include> -->

		
		<xi:include href="Algorithm_Test04.xml" xpointer="length_based.AreaOfRect">
			<xi:fallback></xi:fallback>
		</xi:include>
		
		<!-- not supported!
		<xi:include href="Algorithm_Test04.xml" xpointer="xmlns(alg=https://github.com/galina-p-tuwien/digital_guidelines/algorithm) xpointer(//alg:Algorithm)">
			<xi:fallback></xi:fallback>
		</xi:include>
		-->

	</alg:Algorithms>


	<alg:Connections>
		
		<alg:Connection source_algorithm="length_based.AreaOfRect" source_output="length_based.area" 
					    target_algorithm="length_based.VolumeOfBox" tagret_input="length_based.baseArea" />

	</alg:Connections>
	
</alg:AlgorithmLibrary>
